'use client'
import {useEffect, useState} from 'react'
import {ArrowRight, Check, ChevronLeft, Users, RotateCcw} from 'lucide-react'
import {Customer, SOURCES, Source, addVisit, maskPhone, normalizePhone} from '../lib/domain'
import {initialCustomers} from '../lib/mock-data'

function Kiosk({customers,setCustomers}:{customers:Customer[];setCustomers:(v:Customer[])=>void}){
 const [step,setStep]=useState<'phone'|'source'|'done'>('phone'); const [phone,setPhone]=useState(''); const [existing,setExisting]=useState<Customer|null>(null)
 const syncVisit=async(source?:Source)=>{const response=await fetch('/api/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,source})});if(!response.ok)throw new Error('sync failed');return (await response.json()).customer as Customer}
 const submitPhone=async()=>{const normalized=normalizePhone(phone); if(normalized.length<10)return; const found=customers.find(c=>c.phone===normalized); if(found){try{const updated=await syncVisit();setCustomers(customers.map(c=>c.id===updated.id?updated:c));setExisting(updated)}catch{const updated=addVisit(found);setCustomers(customers.map(c=>c.id===found.id?updated:c));setExisting(updated)}setStep('done')}else{setStep('source')}}
 const selectSource=async(source:Source)=>{try{const updated=await syncVisit(source);setCustomers([...customers.filter(c=>c.phone!==updated.phone),updated]);setExisting(updated)}catch{const c:Customer={id:crypto.randomUUID(),phone:normalizePhone(phone),source,visits:0,points:0,lastVisit:new Date().toISOString().slice(0,10)};const updated=addVisit(c,source);setCustomers([...customers,updated]);setExisting(updated)}setStep('done')}
 return <div className="kiosk"><div className="kiosk-card">{step==='phone'&&<><span className="step">오늘도 반가워요 · 1 / 2</span><h1>전화번호를 입력하고<br/>포인트를 적립하세요</h1><p>방문 기록은 안전하게 관리되며<br/>적립은 3초 안에 끝나요.</p><input autoFocus className="phone-input" value={phone} onChange={e=>setPhone(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submitPhone()} placeholder="010 0000 0000" inputMode="numeric"/><button className="primary" onClick={submitPhone}>포인트 적립하기 <ArrowRight size={17} style={{verticalAlign:'middle'}}/></button></>}{step==='source'&&<><button className="ghost" onClick={()=>setStep('phone')}><ChevronLeft size={15} style={{verticalAlign:'middle'}}/> 번호 다시 입력</button><span className="step">처음 오셨군요 · 2 / 2</span><h1>어디에서<br/>알고 오셨어요?</h1><p>한 번만 알려주시면 더 좋은 소식으로<br/>보답할게요.</p><div className="choices">{SOURCES.map(s=><button className="choice" key={s} onClick={()=>selectSource(s)}>{s}</button>)}</div></>}{step==='done'&&<><div className="success-icon"><Check size={36}/></div><h1>적립 완료!</h1><p>{existing?.visits}번째 방문을 기록했어요.<br/>다음에도 편하게 들러주세요.</p><div className="reward"><span>현재 포인트</span><strong>{existing?.points} P</strong></div><button className="primary" onClick={()=>{setStep('phone');setPhone('');setExisting(null)}}>다음 고객 적립하기</button></>}<div className="demo-note">매장 멤버십 데모 · 데이터는 이 브라우저에 저장됩니다</div></div></div>
}
function Dashboard({customers}:{customers:Customer[]}){const total=customers.length;const visits=customers.reduce((a,c)=>a+c.visits,0);const repeat=customers.filter(c=>c.visits>1).length;const counts=SOURCES.map(s=>({s,n:customers.filter(c=>c.source===s).length}));const max=Math.max(...counts.map(x=>x.n),1);return <main className="main"><div className="hero"><div><div className="eyebrow">Member intelligence</div><h1 className="title">고객이 다시 오는 이유를<br/>매일 확인하세요.</h1><div className="sub">매장 멤버십 현황과 고객 유입경로를 한눈에 볼 수 있어요.</div></div><div className="date">2026년 8월 21일</div></div><div className="grid"><div className="stat"><div className="stat-label">전체 고객</div><div className="stat-value">{total}</div><div className="stat-note">+12% 이번 달</div></div><div className="stat"><div className="stat-label">누적 방문</div><div className="stat-value">{visits}</div><div className="stat-note">+8% 지난 달 대비</div></div><div className="stat"><div className="stat-label">재방문 고객</div><div className="stat-value">{repeat}</div><div className="stat-note">전체의 {total?Math.round(repeat/total*100):0}%</div></div><div className="stat"><div className="stat-label">이번 달 적립</div><div className="stat-value">{visits} P</div><div className="stat-note">고객에게 돌아간 가치</div></div></div><div className="dash-grid"><section className="panel"><div className="panel-title">방문 흐름 <span className="pill">최근 7일</span></div><div className="bars">{[32,48,40,68,54,76,92].map((n,i)=><div className="bar-wrap" key={i}><div className={'bar '+(i===6?'today':'')} style={{height:n+'%'}}/><div className="bar-label">{['15','16','17','18','19','20','오늘'][i]}</div></div>)}</div></section><section className="panel"><div className="panel-title">고객 유입경로 <span className="pill">전체</span></div>{counts.map(x=><div className="source-row" key={x.s}><div className="source-name">{x.s}</div><div className="track"><div className="fill" style={{width:(x.n/max*100)+'%'}}/></div><div className="source-pct">{x.n}명</div></div>)}</section></div><section className="panel" style={{marginTop:14}}><div className="panel-title">최근 고객 <span className="pill"><Users size={13} style={{verticalAlign:'-2px'}}/> {total}명</span></div>{customers.slice().reverse().map(c=><div className="customer-row" key={c.id}><div className="customer-main"><div className="avatar">{c.phone.slice(-2)}</div><div><div className="customer-name">{maskPhone(c.phone)}</div><div className="customer-meta">{c.source??'기존 고객'} · {c.visits}회 방문 · 최근 {c.lastVisit}</div></div></div><div className="customer-points">{c.points} P</div></div>)}</section></main>}
export default function Home(){const [mode,setMode]=useState<'kiosk'|'dashboard'>('kiosk');const [customers,setCustomers]=useState<Customer[]>(initialCustomers);useEffect(()=>{const saved=localStorage.getItem('loop-customers');if(saved)setCustomers(JSON.parse(saved))},[]);useEffect(()=>{localStorage.setItem('loop-customers',JSON.stringify(customers))},[customers]);return <div className="shell"><header className="topbar"><div className="brand"><div className="mark">L</div> LOOP</div><div className="switcher"><button className={mode==='kiosk'?'active':''} onClick={()=>setMode('kiosk')}>고객 화면</button><button className={mode==='dashboard'?'active':''} onClick={()=>setMode('dashboard')}>관리자 보기</button></div></header>{mode==='kiosk'?<Kiosk customers={customers} setCustomers={setCustomers}/>:<Dashboard customers={customers}/>}</div>}
